smoke test now started always for faster feedback

diff --git a/.github/workflows/github-ci.yaml b/.github/workflows/github-ci.yaml
--- a/.github/workflows/github-ci.yaml
+++ b/.github/workflows/github-ci.yaml
@@ -2,6 +2,8 @@ name: CI/CD Pipeline
 env:
   IMAGE_HTML: component-html
   IMAGE_SERVER: component-server
+  IMAGE_WINSLOW: ${{ vars.DOCKER_REGISTRY_WINSLOW }}
+  TAG: ""
 on:
   push:
     branches:
@@ -111,14 +113,81 @@ jobs:
           name: winslow-ui-ng_${{ github.run_id }}
           path: winslow-ui-ng
 
-  publish-validator:
+  smoke-test:
     runs-on: ubuntu-latest
     needs:
       - server-test
       - server-build
       - html-build
-    outputs:
-      TAG: ${{ steps.determine_tag.outputs.TAG }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Download backend
+        uses: actions/download-artifact@v4
+        with:
+          name: jar-files-${{ github.run_id }}
+          path: .
+      - name: Build backend image
+        run: |
+          docker build . -t $IMAGE_SERVER
+
+      - name: Download frontend
+        uses: actions/download-artifact@v4
+        with:
+          name: winslow-ui-ng_${{ github.run_id }}
+          path: ./winslow-ui-ng
+      - name: Build frontend image
+        run: |
+          mv winslow-ui-ng ui-ng/winslow-ui-ng
+          cd ui-ng
+          docker build . -t $IMAGE_HTML
+
+      - name: Set winslow image tag
+        run: |
+          echo "TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
+
+      - name: Build winslow:${{ env.TAG }}
+        run: |
+          cd node
+          docker build . -t $IMAGE_WINSLOW:$TAG --build-arg COMPONENT_HTML=$IMAGE_HTML --build-arg COMPONENT_SERVER=$IMAGE_SERVER
+
+      - name: Prepare upload of winslow:${{ env.TAG }} image to github
+        run: |
+          docker save $IMAGE_WINSLOW:$TAG -o WINSLOW-${TAG}.tar
+      - name: Upload winslow:${{ env.TAG }} image to github
+        uses: actions/upload-artifact@v4
+        with:
+          retention-days: 1
+          compression-level: 9
+          name: WINSLOW_$TAG-${{ github.run_id }}
+          path: |
+            *.tar
+
+      - name: Smoke test winslow:${{ env.TAG }}
+        run: |
+          docker run -it -d --rm -e WINSLOW_DEV_ENV=true -e WINSLOW_DEV_REMOTE_USER=example -e WINSLOW_ROOT_USERS=example -e WINSLOW_WORK_DIRECTORY=/tmp/workdir -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock $IMAGE_WINSLOW:$TAG
+          success=false
+          for i in {1..20}; do
+            echo "Attempt $i: Checking if application is up..."
+            if curl -s -X GET "http://localhost:8080/api/v1/users" -H "accept: */*" | grep -q example; then
+              echo "Application is up and running, and User 'example' was found."
+              success=true
+              break
+              else
+                echo "Application is not ready yet or User 'example' was not found. Retrying in 5 seconds..."
+                sleep 5
+            fi
+            done
+          
+            if [[ "$success" == false ]]; then
+              echo "Failed to connect to application or 'example' was not found after $i tries."
+              echo "Smoke test failed."
+              exit 1
+            fi
+
+  publish-validator:
+    runs-on: ubuntu-latest
+    needs:
+      - smoke-test
     steps:
       - name: Determine image tag
         id: determine_tag
@@ -131,16 +200,13 @@ jobs:
             TAG=${GITHUB_REF_NAME}-dev
           fi 
           echo $TAG
-          echo "TAG=$TAG" >> $GITHUB_OUTPUT
+          echo "TAG=$TAG" >> $GITHUB_ENV
 
   publish-winslow-image:
     runs-on: ubuntu-latest
-    if: needs.publish-validator.outputs.TAG != ''
+    if: env.TAG != ''
     needs:
       - publish-validator
-    env:
-      TAG: ${{ needs.publish-validator.outputs.TAG }}
-      IMAGE_WINSLOW: ${{ vars.DOCKER_REGISTRY_WINSLOW }}
     steps:
       - uses: actions/checkout@v4
       - name: Download backend
